name: Latest Arthurolg blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'

jobs:
  update-readme-with-arthurolg-blog:
    name: Update this repo's README with latest arthurolg.com posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
					comment_tag_name: 'BLOG-ALG'
          feed_list: 'https://arthurolg.com/index.xml'
