name: Latest Dev.to blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 0 * * *'

jobs:
  update-readme-with-dev-to-blog:
    name: Update this repo's README with latest Dev.to posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: 'BLOG-DEV'
          feed_list: 'https://dev.to/feed/lgzarturo'
